name: Publish package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    name: Publish package on NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nodejs 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.4
          registry: https://registry.npmjs.org/
          run_install: |
            - args: [--frozen-lockfile, --dev]

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    name: Publish package on Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nodejs 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.4
          registry: https://npm.pkg.github.com/
          run_install: |
            - args: [--frozen-lockfile, --dev]

      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
